'''event-insight.py
    Proof of concept script for the event insight tool. Console-based wrapper for event-insight-lib.py'''

import argparse
import event_insight_lib

def main():
	token = event_insight_lib.generateToken()
	a = event_insight_lib.annotateText("""The Intrepid Museum’s new exhibition On the Line: Intrepid and the Vietnam War explores the events and impact of the Vietnam War through the lens of Intrepid’s history. The exhibition, which coincides with the 40th anniversary of the conclusion of the war, offers a site-specific immersion into an important chapter of American history.The legendary aircraft carrier Intrepid served three tours of duty in Vietnam between 1966 and 1969. Set within the very spaces where men lived and served, the exhibition focuses on the experiences of Intrepid and its crew “on the line”—the periods when the ship was active in the Gulf of Tonkin, launching aircraft for missions over mainland Vietnam. This localized history serves as the starting point for understanding the larger historical landscape, including the Cold War, Operation Rolling Thunder and protests at home. The exhibition includes artifacts, photographs and film clips from the Museum’s collection, many of which are on display for the first time. The exhibition also draws from the Museum’s Oral History Project, an initiative launched in 2013 to record and preserve the stories of those who served on Intrepid, offering visitors the chance to hear the experiences of veterans in their own words, and to learn history firsthand. The exhibition is free with the price of admission. In conjunction with the exhibition, the Museum is offering education programs for teachers and students, and a series of public programs to generate conversation and artistic expression. Bank of America is generously providing free Museum admission to U.S. active military, retired military and veterans. Proper ID is requested, and tickets may only be obtained at the Museum Box Office. If you are interested in supporting the exhibition, please click here. All gifts are fully tax-deductible and donors of $250 or more will be acknowledged in the exhibition.""", token)
	b = event_insight_lib.annotateText("""Join the National Air and Space Society for our Vice Adm. Donald D. Engen Flight Jacket Night lecture, featuring engineer and stratospheric explorer Alan Eustace.  Launching at 7:00 am on October 24, 2014, Alan Eustace and the StratEx team set three new world records: highest exit altitude at 41,422 meters (135,899 feet), longest distance of fall with drogue at 37,623 meters (123,435 feet), and highest vertical speed with drogue 1,320 km/hr (820 mph). He was carried aloft by a plastic balloon that stood almost 137 meters (450 feet) tall at launch. Climbing at about 305-meters (1,000-feet) a minute, it took 2.5 hours to reach his top altitude. He was safely back on the ground just 15 minutes after cutting loose from the balloon. Eustace retired as Senior Vice President of Knowledge in April 2015 after 13 years with Google. In his last three years at Google, he worked with the world-class StratEx team to build and test a scuba-like system for the exploration of the stratosphere. His work with the StratEx team was a 2014 finalist for the Collier Award, the most prestigious award in aviation. He was also recognized as the winner of the 2014 Laureus Award for Action Sports. The lecture is for members of the Museum's National Air and Space Society and their guests. There is no charge to attend, but advance reservations are required. Visit airandspace.si.edu/membertickets to reserve yours. Seating is limited. There will also be a buffet reception before the lecture with Mr. Eustace for Society members at the Mercury Friendship 7 level and higher. For more information, call 202.633.2603 or email nasmmembership@si.edu. Flight jacket optional.  The Museum's doors on Jefferson Drive will be closed for the evening. Please use the Independence Avenue entrance.""", token)
	c = event_insight_lib.annotateText("""WAR/PHOTOGRAPHY: Images of Armed Conflict and Its Aftermath explores the experience of war with an unprecedented collection of 400 photographic prints, books, magazines, albums, and camera equipment, bringing together iconic and unknown images taken by members of the military, commercial portraitists, journalists, amateurs, artists, and numerous Pulitzer Prize–winning photographers. Including the work of some 255 photographers from around the globe who have covered conflicts over the last 166 years, WAR/PHOTOGRAPHY examines the interrelationship between war and photography, reveals the evolution of the medium by which war is recorded and remembered, and explores the range of experience of armed conflict: recruitment, training, embarkation, daily routine, battle, death and destruction, homecoming, and remembrance. In addition to depicting the phases of war, WAR/PHOTOGRAPHY includes portraits of servicemen, military and political leaders, and civilians and refugees. The objects on view include rare daguerreotypes and vintage photographs, such as Roger Fenton’s iconic The Valley of the Shadow of Death (1855) from the Crimean War and an early print of Joe Rosenthal’s Old Glory Goes Up on Mount Suribachi, Iwo Jima. More recent images include a 2008 photograph of the Battle Company of the 173rd Airborne Brigade in eastern Afghanistan by Tim Hetherington. WAR/PHOTOGRAPHY: Images of Armed Conflict and Its Aftermath has been organized by the Museum of Fine Arts, Houston, curatorial team of Anne Wilkes Tucker, Will Michels, and Natalie Zelt. The Brooklyn presentation is organized by Tricia Laughlin Bloom, Associate Curator of Exhibitions, Brooklyn Museum. Generous support for the exhibition in Brooklyn has been provided by the Robert Mapplethorpe Foundation and the Martha A. and Robert S. Rubin Exhibition Fund.""", token)

if __name__ == "__main__":
    main()